version: "3.8"

networks:
  corp:
    driver: bridge

services:
  backend:
    container_name: backend
    build:
      context: ./
      cache_from:
        - my-base-image:nx-base
      dockerfile: ./apps/backend/Dockerfile
      args:
        NODE_ENV: "development"
        BUILD_FLAG: ""
    image: backend:nx-dev
    ports:
      - 3333:3333
    environment:
      NODE_ENV: "development"
      PORT: 3333
    networks:
      - corp
    restart: on-failure

  client:
    container_name: client
    build:
      context: ./
      cache_from:
        - nginx:1.19.2
      dockerfile: ./apps/client/Dockerfile
      args:
        NODE_ENV: "development"
        BUILD_FLAG: ""
    image: client:nx-dev
    ports:
      - 4200:80
    environment:
      NODE_ENV: "development"
      PORT: 4200
    networks:
      - corp
    restart: on-failure