/**
 * Generated by orval v6.7.1 🍺
 * Do not edit manually.
 * Planning Poker API
 * OpenAPI spec version: 1.0
 */
import type { VotingDto } from './votingDto';
import type { BoardDtoCurrentVoting } from './boardDtoCurrentVoting';

export interface BoardDto {
  players: string[];
  votings: VotingDto[];
  name: string;
  currentVoting: BoardDtoCurrentVoting;
}
