/**
 * Generated by orval v6.7.1 🍺
 * Do not edit manually.
 * Planning Poker API
 * OpenAPI spec version: 1.0
 */
import type { PlayerDto } from './playerDto';
import type { IssueDto } from './issueDto';

export interface GetResultSuccessDto {
  finished: boolean;
  gameName: string;
  players: PlayerDto[];
  tasks: string[];
  storyPoints: number | null;
  id: string;
  issues: IssueDto[];
}
