/**
 * Generated by orval v6.7.1 🍺
 * Do not edit manually.
 * Planning Poker API
 * OpenAPI spec version: 1.0
 */
import type { PlayerDto } from './playerDto';

export interface GetResultSuccessDto {
  gameName: string;
  players: PlayerDto[];
}
