/**
 * Generated by orval v6.7.1 🍺
 * Do not edit manually.
 * Planning Poker API
 * OpenAPI spec version: 1.0
 */
import type { IssueDto } from './issueDto';

export interface SetIssuesBody {
  issues: IssueDto[];
}
