/**
 * Generated by orval v6.7.1 🍺
 * Do not edit manually.
 * Planning Poker API
 * OpenAPI spec version: 1.0
 */

export interface UserDTO {
  userId: number;
  username: string;
  password: string;
  rooms: string[];
}
