/**
 * Generated by orval v6.7.1 🍺
 * Do not edit manually.
 * Cats example
 * The cats API description
 * OpenAPI spec version: 1.0
 */
import type { VoteDto } from './voteDto';

export interface VotingDto {
  question: string;
  finished: boolean;
  participants: VoteDto[];
}
