/**
 * Generated by orval v6.7.1 🍺
 * Do not edit manually.
 * Planning Poker API
 * OpenAPI spec version: 1.0
 */
import type {
  RestartRequest,
  GetResultSuccessDto,
  GetResultRequest,
  PlayerDto
} from './schemas'
import { customInstance, ErrorType } from './custom-instance'


  export const appControllerGetData = (
    
 ) => {
      return customInstance<void>(
      {url: `/api`, method: 'get'
    },
      );
    }
  
export const votingControllerStartNew = (
    restartRequest: RestartRequest,
 ) => {
      return customInstance<void>(
      {url: `/api/voting/startNew`, method: 'post',
      headers: {'Content-Type': 'application/json'},
      data: restartRequest
    },
      );
    }
  
export const votingControllerGetResult = (
    getResultRequest: GetResultRequest,
 ) => {
      return customInstance<GetResultSuccessDto>(
      {url: `/api/voting/getResult`, method: 'get',
      headers: {'Content-Type': 'application/json'}
    },
      );
    }
  
export const votingControllerVote = (
    playerDto: PlayerDto,
 ) => {
      return customInstance<void>(
      {url: `/api/voting/vote`, method: 'post',
      headers: {'Content-Type': 'application/json'},
      data: playerDto
    },
      );
    }
  

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AsyncReturnType<
T extends (...args: any) => Promise<any>
> = T extends (...args: any) => Promise<infer R> ? R : any;

export type AppControllerGetDataResult = NonNullable<AsyncReturnType<typeof appControllerGetData>>
export type VotingControllerStartNewResult = NonNullable<AsyncReturnType<typeof votingControllerStartNew>>
export type VotingControllerGetResultResult = NonNullable<AsyncReturnType<typeof votingControllerGetResult>>
export type VotingControllerVoteResult = NonNullable<AsyncReturnType<typeof votingControllerVote>>